apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-filebeat
  labels:
    name: app-filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-filebeat
  template:
    metadata:
      labels:
        name: app-filebeat
    spec:
      containers:
      - name: app-filebeat
        image: rogerg18/sowa:latest
        volumeMounts:
         - name: log-output
           mountPath: /var/log/
      - name: filebeat
        image: elastic/filebeat:7.8.0
        env:
        - name: LOGSTASH_HOSTS
          value: {{ .Values.global.hostIp }}:{{ .Values.ports.logstash }}
        args: [
          "-c", "/etc/filebeat/filebeat.yml",
          "-e"
         ]
        volumeMounts:
         - name: log-output
           mountPath: /var/log/
         - name: filebeat-config
           mountPath: /etc/filebeat/
      volumes:
       - name: log-output
         emptyDir: {}
       - name: filebeat-config
         configMap:
           name: filebeat-config
           items:
           - key: filebeat.yml
             path: filebeat.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
{{ .Files.Get "filebeat.yml" | indent 4 }}
